### ISSUE TITLE
kubeconfig issue

### ISSUE THREAD

**Issue by tpargmdiaz** [hardillb/multi-tenant-node-red-k8s#1]
Hi Ben!

 First of all congrats, awesome work!  I was trying to deploy the workloads in AWS EKS and found it was quite challenging. On the README file it says:

Running `./setup.sh` in the root directory of the project will generate a `deployment/secret.yml` file that holds the details for connecting to the Kubernetes API and and the `settings.js` for the management app.

I ran the script but no secret.yml was generated. In the nodered-manager pod I get these error log:

```
internal/fs/utils.js:269
    throw err;
    

Error: ENOENT: no such file or directory, open '~/.kube/config'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at KubeConfig.loadFromFile (/usr/src/app/node_modules/@kubernetes/client-node/dist/config.js:65:32)
    at Object.<anonymous> (/usr/src/app/index.js:21:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '~/.kube/config'
}
```

Any help is much appreciated!

Best regards,

Mauricio

**Comment by hardillb** [comment]
The `README.md` has been updated to reflect a later change in which files setup.sh creates/modified, `deployment/secret.yml` is no longer used.

As to why you get that error I really can't say as line 21 of `index.js` in the management app should be commented out in all the code I have checked so you have obviously changed things.

All I can suggest is make sure you have pulled the latest code including all the submodules.
