### ISSUE TITLE
Manager issue: kubeconfig is not defined

### ISSUE THREAD

**Issue by tpargmdiaz** [hardillb/multi-tenant-node-red-k8s#3]
Hi Ben, I have downloaded the code with the latest changes including the submodules as you indicated. This time the container node-red-manager is not starting cause kubeconfig is not defined. Here is the log:

```

k logs pod/node-red-multi-tenant-9b7488646-xmfzt node-red-manager
/usr/src/app/index.js:27
kubeconfig.loadFromCluster()
^

ReferenceError: kubeconfig is not defined
    at Object.<anonymous> (/usr/src/app/index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

Is the manager supposed to copy the .kube/config file from my local machine? 

Thanks!

Mauricio

**Comment by hardillb** [comment]
No, line 20 should not be comment out.

Fixed, you'll need to re-pull (including submodules)

**Comment by tpargmdiaz** [comment]
It worked! Thank you Ben, you saved me!
